// Generated by CoffeeScript 1.7.1
var notify;

notify = {
    socketUrl: "" + location.protocol + "//" + location.hostname + ":8899/notify",
    socket: null,
    isStart: 0
};

notify.connect = function () {
    if (notify.socket == null) {
        notify.socket = io.connect(notify.socketUrl);
        notify.bindMsg(notify.socket);
    } else if (!notify.socket.socket.connected) {
        notify.socket.socket.connect();
        notify.bindMsg(notify.socket);
    }
    if (!notify.isStart) {
        notify.startNotify();
    }
};

notify.bindMsg = function (socket) {
    return socket.on('notify', function (data) {
        if (data && data.update === 1) {
            return domFunc.getNotificationList();
        }
    });
};

notify.startNotify = function () {
    var data;
    if (!$.cookie('loginMail')) {
        return;
    }
    notify.isStart = 1;
    data = {
        user: $.cookie('loginMail'),
        time: tools.time()
    };
    notify.socket.emit('start', data);
};
