// Generated by CoffeeScript 1.7.1

/*
 @Author Ansel
 @params 
    options 包含name， desc， other
      other可以添加更丰富的信息
    obj Kinetic 对象
 @example 
    $.tips(options, obj)
    $.tips('hide') 可以隐藏当前画布的tips
 */
(function($) {
  var _msg;
  _msg = {
    'name_require': '组件名字不能为空',
    'name_available_en_cn_len64': '组件名字最短两位，最长64位'
  };
  $.extend({
    validate: function(str, options) {
      var optKey, result, _i, _len;
      result = true;
      for (_i = 0, _len = options.length; _i < _len; _i++) {
        optKey = options[_i];
        if (optKey === 'name_require') {
          if ('' === $.trim(str)) {
            $.notify({
              msg: _msg[optKey],
              type: 'danger'
            });
            result = false;
          }
        } else if (optKey === 'name_available_en_cn_len64') {
          if (!/^.{2,64}$/.test(str)) {
            $.notify({
              msg: _msg[optKey],
              type: 'danger'
            });
            result = false;
          }
        }
      }
      return result;
    }
  });
})($);
