// Generated by CoffeeScript 1.7.1
var data;

data = {
  layer: {},
  ecs: {},
  rds: {},
  slb: {},
  oss: {},
  ots: {},
  ocs: {},
  cdn: {},
  odps: {},
  yundun: {},
  jiankong: {},
  diy: {},
  line: {},
  mqs: {},
  oas: {},
  opensearch: {},
  pts: {},
  sls: {}
};
