// Generated by CoffeeScript 1.7.1

/*
usage:
price({
      type:'ecs',
      data:{
          cpu:2,
          mem:1536,
          bandwidth:2,
          storage:20
      },
      time:12
})
price({
      type:'rds',
      data:{
          dbtype:'mssql',
          mem:4000,
          storage:20
      },
      time:12
})
 */
$(function() {
  window.price = function(obj) {
    var isHK, _price;
    if ("undefined" === typeof obj.type) {
      return false;
    }
    if ("undefined" === typeof obj.data) {
      return false;
    }
    if ("undefined" === typeof obj.time) {
      return false;
    }
    if ("number" !== typeof obj.amount) {
      obj.amount = 1;
    }
    _price = 0;
    isHK = false;
    if ($.cookie('regionId') === 'cn-hongkong') {
      isHK = true;
    }
    switch (obj.type) {
      case 'ecs':
        switch (obj.data.cpu) {
          case 1:
            switch (obj.data.mem) {
              case 512:
                _price += 32;
                break;
              case 1024:
                _price += 52;
                break;
              case 1536:
                _price += 71;
                break;
              case 2048:
                _price += 96;
                break;
              case 4096:
                _price += 187;
            }
            break;
          case 2:
            switch (obj.data.mem) {
              case 1536:
                _price += 164;
                break;
              case 2048:
                _price += 185;
                break;
              case 2560:
                _price += 208;
                break;
              case 4096:
                _price += 248;
                break;
              case 8192:
                _price += 374;
            }
            break;
          case 4:
            switch (obj.data.mem) {
              case 4096:
                _price += 370;
                break;
              case 8192:
                _price += 496;
                break;
              case 12288:
                _price += 727;
                break;
              case 16384:
                _price += 748;
            }
            break;
          case 8:
            switch (obj.data.mem) {
              case 8192:
                _price += 740;
                break;
              case 12288:
                _price += 921;
                break;
              case 16384:
                _price += 992;
                break;
              case 24576:
                _price += 1454;
                break;
              case 32768:
                _price += 1496;
            }
            break;
          case 16:
            switch (obj.data.mem) {
              case 65536:
                _price += 2992;
            }
        }
        if (obj.data.bandwidth >= 1) {
          _price += 23;
        }
        if (obj.data.bandwidth >= 2) {
          _price += 23;
        }
        if (obj.data.bandwidth >= 3) {
          _price += 25;
        }
        if (obj.data.bandwidth >= 4) {
          _price += 25;
        }
        if (obj.data.bandwidth >= 5) {
          _price += 29;
        }
        if (obj.data.bandwidth > 5) {
          _price += 100 * (obj.data.bandwidth - 5);
        }
        _price += 0.36 * obj.data.storage;
        if (obj.time % 12 > 0) {
          _price *= obj.time;
        } else {
          _price *= 10 * obj.time / 12;
        }
        if ($.cookie('regionId') === 'cn-qingdao') {
          _price = _price * 0.9;
        }
        break;
      case 'rds':
        if ("undefined" === typeof obj.data.dbtype) {
          return false;
        }
        switch (obj.data.dbtype.toLowerCase()) {
          case "mysql":
            switch (obj.data.mem) {
              case 240:
                if ($.cookie('regionId') === 'cn-hongkong') {
                  _price += 57;
                } else {
                  _price += 41;
                }
                break;
              case 600:
                _price += 102;
                break;
              case 1200:
                _price += 204;
                break;
              case 2400:
                _price += 408;
                break;
              case 6000:
                _price += 1020;
                break;
              case 12000:
                _price += 2040;
                break;
              case 24000:
                _price += 4080;
                break;
              case 48000:
                _price += 8160;
            }
            break;
          case "mssql":
            switch (obj.data.mem) {
              case 1000:
                _price += 301;
                break;
              case 2000:
                _price += 602;
                break;
              case 4000:
                _price += 1204;
                break;
              case 6000:
                _price += 1805;
                break;
              case 8000:
                _price += 2407;
                break;
              case 12000:
                _price += 3610;
                break;
              case 24000:
                _price += 7220;
                break;
              case 48000:
                _price += 14440;
            }
        }
        _price += obj.data.storage * 0.8;
        if (obj.time % 12 > 0) {
          _price *= obj.time;
        } else {
          _price *= 10 * obj.time / 12;
        }
        if ($.cookie('regionId') === 'cn-qingdao') {
          _price = _price * 0.95;
        }
    }
    _price *= obj.amount;
    return _price;
  };
  window.selEcsPrice = function() {
    var o;
    o = {};
    o.type = "ecs";
    o.time = parseInt($('#remark4Ecs #ecs-buy-time').val());
    o.amount = parseInt($('#remark4Ecs #ecs-buy-amount').val());
    o.data = {};
    o.data.cpu = parseInt($('#remark4Ecs #hd-cpu').val());
    o.data.mem = parseInt($('#remark4Ecs #hd-mem').val());
    o.data.bandwidth = parseInt($('#remark4Ecs #ecs_netSpeed_amount').val());
    o.data.storage = 0;
    if ("number" !== typeof o.time || o.time < 1) {
      o.time = 1;
    }
    $('.diskinput').each(function() {
      return o.data.storage += parseInt($(this).val());
    });
    return NumberHelpers.number_to_currency(price(o), {
      unit: "&#65509;"
    });
  };
  return window.selRdsPrice = function() {
    var o;
    o = {};
    o.type = "rds";
    o.data = {};
    o.data.dbtype = $('#rds-sql-type option:selected').val();
    o.data.mem = parseInt($('#rdsMem').val());
    o.data.storage = parseInt($('#rds-storage-input').val());
    o.time = parseInt($('#rds-buy-time').val());
    return NumberHelpers.number_to_currency(price(o), {
      unit: "&#65509;"
    });
  };
});
