// Generated by CoffeeScript 1.7.1
jQuery.extend({
  notify: function(options) {
    var i, remove, ret, rets, _i, _len, _options;
    remove = function(id) {
      return $("#" + id).fadeOut(function() {
        $("#" + id).remove();
        if ($('#notify-alert-container .alert-bar').size() === 0) {
          return $('#notify-alert-container').remove();
        }
      });
    };
    _options = {
      msg: 'Message',
      type: 'success',
      timeout: 3500,
      _style: '',
      _dismissable: true,
      _color: '',
      _background: '',
      _border: '',
      _borderRadius: '5px',
      _padding: '15px',
      _position: 'relative',
      _display: 'block',
      _top: '0',
      _left: '50%',
      _width: 'auto',
      _minWidth: '500px',
      _minHeight: '20px',
      _zIndex: '9999',
      _classPrefix: 'alert',
      _class: '',
      _dom: '',
      _appendTo: $('#notify-alert-container'),
      _id: 'jqueryNotify' + (new Date).getTime().toString() + parseInt(Math.random() * 1000000),
      _dismissDom: '<button type="button" class="close" style="height:16px;line-height:16px;right:0 !important;right:0;" data-dismiss="alert" aria-hidden="true">×</button>'
    };
    if (_options._appendTo.size() === 0) {
      _options._appendTo = $('<div id="notify-alert-container" style="position:absolute;top:55px;left:50%;"></div>');
      _options._appendTo.appendTo($('body'));
    }
    $.extend(_options, options);
    rets = _options._appendTo.find('.alert-bar .notify-content');
    for (i = _i = 0, _len = rets.length; _i < _len; i = ++_i) {
      ret = rets[i];
      if ($(ret).html() === _options.msg) {
        return;
      }
    }
    if (_options.type) {
      _options._class += " " + _options._classPrefix + "-" + _options.type;
    }
    if (_options._dismissable) {
      _options._class += " " + _options._classPrefix + "-dismissable";
    }
    if (_options._dismissable === false) {
      _options._dismissDom = '';
    }
    if (_options._color !== '') {
      _options._style += " color: " + _options._color;
      _options._style += ";";
    }
    if (_options._background !== '') {
      _options._style += " background: " + _options._background;
      _options._style += ";";
    }
    if (_options._border !== '') {
      _options._style += " border: " + _options._border;
      _options._style += ";";
    }
    if (_options._borderRadius) {
      _options._style += " border-radius: " + _options._borderRadius;
      _options._style += ";";
    }
    if (_options._padding) {
      _options._style += " padding: " + _options._padding;
      _options._style += ";";
    }
    if (_options._position) {
      _options._style += " position: " + _options._position;
      _options._style += ";";
    }
    if (_options._display) {
      _options._style += " display: " + _options._display;
      _options._style += ";";
    }
    if (_options._top) {
      _options._style += " top: " + _options._top;
      _options._style += ";";
    }
    if (_options._left) {
      _options._style += " left: " + _options._left;
      _options._style += ";";
    }
    if (_options._width) {
      _options._style += " width: " + _options._width;
      _options._style += ";";
    }
    if (_options._minWidth) {
      _options._style += " min-width: " + _options._minWidth;
      _options._style += ";";
    }
    if (_options._minHeight) {
      _options._style += " min-height: " + _options._minHeight;
      _options._style += ";";
    }
    if (_options._minWidth) {
      _options._style += " min-width: " + _options._minWidth;
      _options._style += ";";
    }
    if (_options._minWidth) {
      _options._style += " min-width: " + _options._minWidth;
      _options._style += ";";
    }
    if (_options._zIndex) {
      _options._style += " z-index: " + _options._zIndex;
      _options._style += ";";
    }
    _options._dom = ['<div id="', _options._id, '" class="alert-bar', _options._class, '" style="', _options._style, '">', _options._dismissDom, '<span class="notify-content">', _options.msg, '</span>', '</div>'].join('');
    $(_options._dom).appendTo(_options._appendTo);
    $('#' + _options._id).css('margin', '10px -' + ($('#' + _options._id).outerWidth() / 2).toString() + 'px');
    setTimeout(function() {
      return $('#' + _options._id).css('margin', '10px -' + ($('#' + _options._id).outerWidth() / 2).toString() + 'px');
    }, 100);
    if (_options._dismissable) {
      $('#' + _options._id + '.' + _options._classPrefix + '-dismissable .close').on('click', function() {
        return remove(_options._id);
      });
    }
    setTimeout(function() {
      return remove(_options._id);
    }, _options.timeout);
  }
});
