// Generated by CoffeeScript 1.7.1
var SubTask;

SubTask = (function() {
  SubTask.prototype.operate = ['bindIp', 'unbindIp', 'securityGroup', 'del', 'new', 'modifySpec', 'modifyAttr', 'addListener', 'removeListener', 'listenerStatus', 'listenerName', 'addDisk', 'removeDisk'];

  SubTask.prototype.type = ['ecs', 'slb', 'rds', 'ots', 'oss', 'snapshot', 'iso', 'disk'];

  function SubTask(_options) {
    var options;
    options = {
      id: 'subtask-' + tools.guid(),
      desc: '',
      depend: null,
      type: '',
      operate: '',
      options: {},
      preTasks: [],
      preOptions: {},
      status: 'wait'
    };
    $.extend(options, _options);
    if ((options.type == null) || (options.operate == null)) {
      throw new Error('所需要提供的参数不完整');
    }
    if (options.depend && !global.comList.hasOwnProperty(options.depend)) {
      throw new Error('请求的 depend 不存在');
    }
    if (options.desc === '') {
      throw new Error('请设置desc参数');
    }
    this.id = options.id;
    this.desc = options.desc;
    this.depend = options.depend;
    this.type = options.type;
    this.operate = options.operate;
    this.options = options.options;
    this.preTasks = options.preTasks;
    this.preOptions = options.preOptions;
    this.status = options.status;
  }

  return SubTask;

})();
