// Generated by CoffeeScript 1.7.1
var Task;

Task = (function() {
  Task.prototype.operate = ['bindIp', 'unbindIp', 'securityGroup', 'del', 'new', 'modifySpec', 'modifyAttr', 'addHTTPListener', 'addTCPListener', 'setHTTPListener', 'setTCPListener', 'removeListener', 'listenerStatus', 'listenerName', 'addDisk', 'removeDisk', 'addBackendServers', 'removeBackendServers'];

  Task.prototype.type = ['ecs', 'slb', 'rds', 'ots', 'oss', 'snapshot', 'iso'];

  function Task(_options) {
    var options;
    options = {
      id: 'task',
      desc: '',
      amount: 1,
      depend: null,
      type: '',
      operate: '', 
      result: 0,
      subTasks: {},
      nodeId: '',
      key: 'none',
      status: 'wait',
      options: {}
    };
    $.extend(options, _options);
    if ((_options.type == null) || (options.operate == null)) {
      throw new Error('所需要提供的参数不完整');
    }
    if (options.depend && !global.comList.hasOwnProperty(options.depend)) {
      throw new Error('请求的 depend 不存在');
    }
    if (options.desc === '') {
      throw new Error('请设置desc参数');
    }
    this.id = "" + options.id + "-" + options.nodeId + "-" + options.type + "-" + options.operate + "-" + (options.key.replace(/[^\w\-\_\$\@]/, '_'));
    this.desc = options.desc;
    this.amount = options.amount;
    this.depend = options.depend;
    this.type = options.type;
    this.operate = options.operate;
    this.result = options.result;
    this.subTasks = options.subTasks;
    this.nodeId = options.nodeId;
    this.status = options.status;
    this.options = options.options;
    this.key = options.key;
  }

  return Task;

})();
