// Generated by CoffeeScript 1.7.1
var config;

config = {
    domain: 'http://test.jiagouyun.com/',
    assetDir: 'img/',
    comDir: 'img/com/',
    pluginDir: 'img/com-plugin/',
    diskDir: 'img/disk/',
    apidomain: 'http://testapi.jiagouyun.com/'
};

config.chartLine = {
    scaleOverlay: true,
    scaleOverride: false,
    scaleSteps: null,
    scaleStepWidth: null,
    scaleStartValue: null,
    scaleLineColor: "rgba(000.1)",
    scaleLineWidth: 1,
    scaleShowLabels: false,
    scaleLabel: "<%=value%>",
    scaleFontFamily: "'Arial'",
    scaleFontSize: 12,
    scaleFontStyle: "normal",
    scaleFontColor: "#666",
    scaleShowGridLines: true,
    scaleGridLineColor: "rgba(000.05)",
    scaleGridLineWidth: 1,
    bezierCurve: true,
    pointDot: true,
    pointDotRadius: 2,
    pointDotStrokeWidth: 1,
    datasetStroke: true,
    datasetStrokeWidth: 2,
    datasetFill: true,
    animation: false,
    animationSteps: 60,
    animationEasing: "easeOutQuart",
    onAnimationComplete: null
};
