// Generated by CoffeeScript 1.7.1
var loginFunc;

loginFunc = {
  isNew: function() {
    var s, t, url;
    url = document.URL;
    t = url.indexOf('new');
    s = false;
    if (t !== -1) {
      s = true;
    }
    return s;
  },
  userBtnClick: function() {
    if (!loginFunc.isNew()) {
      domFunc.initBindRam();
    }
    $('.dropdown').dropdown();
  },
  myLoginClick: function() {
    $('#login-mail').val('');
    $('#login-pwd').val('');
    $('#label-error').text('');
    $('.control-group').removeClass('error');
  },
  loginBtnClick: function() {
    var checkmail, checkpwd, postData, valMail, valPwd;
    valMail = $('#login-mail').val();
    valPwd = $('#login-pwd').val();
    checkmail = true;
    checkpwd = true;
    if (valPwd !== '') {
      checkpwd = true;
    } else {
      $('#label-error').html('请填写密码');
      $('#login-pwd').parent('.control-group').removeClass('error');
      checkpwd = false;
    }
    if (valMail !== '') {
      if (valMail.search(/^([a-zA-Z0-9_\.-]+)@(([a-zA-Z0-9_-]+)\.)+[a-zA-Z]{2,6}$/) !== 0) {
        $('#label-error').html('请填写正确格式的mail');
        $('#login-mail').parent('.control-group').addClass('error');
        checkmail = false;
      }
    } else {
      $('#label-error').html('请填写mail');
      $('#login-mail').parent('.control-group').removeClass('error');
      checkmail = false;
    }
    if (!checkmail) {
      $('#login-mail').focus();
      return;
    } else if (!checkpwd) {
      $('#login-pwd').focus();
      return;
    } else {
      postData = {
        mail: encodeURIComponent(valMail),
        pwd: encodeURIComponent(valPwd)
      };
      tools.post('/user/login', postData, loginFunc.logincallback);
    }
  },
  logincallback: function(rs) {
    var isnew, loginMail, result, rsCode;
    if (rs) {
      result = rs & 3;
      rsCode = result;
    } else {
      rsCode = 0;
    }
    switch (rsCode) {
      case 0:
        $('#login-pwd').val('');
        $('#label-error').text('登录失败，请重新登录');
        break;
      case 1:
        loginMail = $('#login-mail').val();
        $.cookie('loginMail', loginMail);
        $('#usermail').text($.cookie('loginMail'));
        $('#mylogin,#myreg').hide();
        $('#userinfo').show().text($.cookie('loginMail'));
        $('#comListModelBtn,#scriptBtn,#monitorBtn,#notifyBtn,#structListModelBtn').show();
        isnew = loginFunc.isNew();
        if (isnew) {
          if ($.cookie('savetype')) {
            switch ($.cookie('savetype')) {
              case 'modelshow':
                $('#btnmodelStruct').trigger('click');
                break;
              default:
                $.removeCookie('savetype');
            }
            $.removeCookie('savetype');
          }
          location.replace('/new/');
        } else {
          domFunc.loginSuccessExec();
          loginFunc.isAdmin(loginMail);
          if (loginMail === 'jiagou@jiagouyun.com' || loginMail === '629215660@qq.com') {
            $('.com-adv').show();
          }
          if ($.cookie('savetype')) {
            switch ($.cookie('savetype')) {
              case 'achi':
                $('#saveBtn').trigger('click');
                break;
              case 'layer_confirm':
                $('#layer_confirm').trigger('click');
                break;
              case 'ecs_confirm_pay1':
                $('#ecs_confirm_pay1').trigger('click');
                break;
              case 'rds_confirm':
                $('#rds_confirm').trigger('click');
                break;
              case 'task_confirm':
                $('#task-confirm-btn').trigger('click');
                break;
              case 'getallcom':
                domFunc.onComListModelBtnClick(1, true);
                break;
              default:
                $.removeCookie('savetype');
            }
            $.removeCookie('savetype');
          }
          canFunc.getCustomComList();
          domFunc.initStructListModel();
        }
        $('#loginModal').modal('hide');
        notify.connect();
        break;
      case 2:
        $('#login-pwd').val('');
        $('#label-error').text('登录密码错误');
        break;
      case 3:
        $('#login-pwd').val('');
        $('#label-error').text('邮箱不存在');
    }
  },
  loginOutClick: function() {
    if (location.pathname.toLowerCase().substr(1) === 'main' && $.cookie('structname')) {
      bootbox.dialog({
        message: '登出之前是否保存架构？若不保存，现有架构将会丢失。',
        buttons: {
          success: {
            label: '保存',
            className: 'btn-success',
            callback: function() {
              global.needLogout = true;
              domFunc.saveStruct();
            }
          },
          danger: {
            label: '不保存',
            className: 'btn-danger',
            callback: function() {
              loginFunc.logoutClear();
            }
          },
          cancel: {
            label: '取消',
            className: 'btn-default',
            callback: function() {}
          }
        }
      });
    } else {
      loginFunc.logoutClear();
    }
  },
  logoutClear: function() {
    return $.post('/user/logout', function(data) {
      if (data === 'ok') {
        tools.clearLoginInfo();
        location.replace('/new');
      } else {
        bootbox.alert('服务器错误，请重试。');
      }
    });
  },
  regBtnClick: function() {
    var checkmail, checkpwd, checkrepwd, data, valDigits, valMail, valPwd, valRePwd;
    $('#reg-label-error').text('');
    $('.control-group').removeClass('error');
    valRePwd = $('#reg-repwd').val();
    valPwd = $('#reg-pwd').val();
    valMail = $('#reg-mail').val();
    valDigits = $('#reg-digits').val();
    checkmail = true;
    checkpwd = true;
    checkrepwd = true;
    if (valRePwd !== '') {
      if (valRePwd !== valPwd) {
        $('#reg-label-error').html('确认密码与密码不一致');
        $('#reg-repwd').parent('.control-group').addClass('error');
        checkrepwd = false;
      }
    } else {
      $('#reg-label-error').html('请填写确认密码');
      $('#reg-repwd').parent('.control-group').removeClass('error');
      checkrepwd = false;
    }
    if (valPwd !== '') {
      if (valPwd.length < 6) {
        $('#reg-label-error').html('密码不能少于6位');
        $('#reg-pwd').parent('.control-group').addClass('error');
        checkpwd = false;
      }
    } else {
      $('#reg-label-error').html('请填写密码');
      $('#reg-pwd').parent('.control-group').removeClass('error');
      checkpwd = false;
    }
    if (valMail !== '') {
      if (valMail.search(/^([a-zA-Z0-9_\.-]+)@(([a-zA-Z0-9_-]+)\.)+[a-zA-Z]{2,6}$/) !== 0) {
        $('#reg-label-error').html('请填写正确格式的mail');
        $('#reg-mail').parent('.control-group').addClass('error');
        checkmail = false;
      }
    } else {
      $('#reg-label-error').html('请填写mail');
      $('#reg-mail').parent('.control-group').removeClass('error');
      checkmail = false;
    }
    if (!checkmail) {
      $('#reg-mail').focus();
      return;
    } else if (!checkpwd) {
      $('#reg-pwd').focus();
      return;
    } else if (!checkrepwd) {
      $('#reg-repwd').focus();
      return;
    } else {
      data = {
        mail: encodeURIComponent(valMail),
        pwd: encodeURIComponent(valPwd),
        digits: encodeURIComponent(valDigits)
      };
      tools.post('/user/reg', data, loginFunc.regcallback);
    }
  },
  regcallback: function(rs) {
    var isnew, regMail, rsCode;
    rsCode = parseInt(rs);
    switch (rsCode) {
      case 0:
        $('#reg-pwd').val('');
        $('#reg-repwd').val('');
        $('#reg-label-error').text('注册失败，请刷新以后重新注册');
        break;
      case 1:
        $('#regModal,#loginModal').modal('hide');
        regMail = $('#reg-mail').val();
        $.cookie('loginMail', regMail);
        $('#usermail').text($.cookie('loginMail'));
        $('#mylogin,#myreg').hide();
        $('#userinfo').show().text($.cookie('loginMail'));
        $('#comListModelBtn,#scriptBtn,#monitorBtn,#notifyBtn,#structListModelBtn').show();
        $('#regModal').modal('hide');
        isnew = loginFunc.isNew();
        if (!isnew) {
          domFunc.loginSuccessExec();
          loginFunc.isAdmin(regMail);
          if ($.cookie('savetype')) {
            switch ($.cookie('savetype')) {
              case 'achi':
                $('#saveBtn').trigger('click');
                break;
              case 'layer_confirm':
                $('#layer_confirm').trigger('click');
                break;
              case 'ecs_confirm_pay1':
                $('#ecs_confirm_pay1').trigger('click');
                break;
              case 'rds_confirm':
                $('#rds_confirm').trigger('click');
                break;
              default:
                $.removeCookie('savetype');
            }
            $.removeCookie('savetype');
          }
        }
        break;
      case 2:
        $('#reg-digits').val('');
        $('#reg-label-error').text('验证码不正确');
        break;
      case 3:
        $('#reg-digits').val('');
        $('#reg-label-error').text('该帐号已被注册');
    }
    $('#regModal input[type=password]').val('');
    tools.reloadCaptcha();
  },
  myRegClick: function() {
    $('.control-group').removeClass('error');
    $('#reg-mail').val('');
    $('#reg-pwd').val('');
    $('#reg-repwd').val('');
    $('#reg-digits').val('');
    $('#reg-label-error').text('');
    tools.reloadCaptcha();
  },
  myAliLoginClick: function() {
    var wlogin;
    $.cookie('showplace', 'new');
    wlogin = window.open(resources.loginurl['ali'], 'alilogin', 'width=900,height=570', false);
    wlogin.document.title = '正在跳转中...';
  },
  myWeiboLoginClick: function() {
    var wlogin;
    $.cookie('showplace', 'new');
    wlogin = window.open(resources.loginurl['weibo'], 'alilogin', 'width=900,height=570', false);
    wlogin.document.title = '正在跳转中...';
  },
  myQqLoginClick: function() {
    var wlogin;
    $.cookie('showplace', 'new');
    wlogin = window.open(resources.loginurl['qq'], 'alilogin', 'width=900,height=570', false);
    wlogin.document.title = '正在跳转中...';
  },
  loginsucback: function(loginMail, source) {
    var postUserData;
    loginMail = $.cookie('loginMail');
    $('#usermail').text(loginMail);
    $('#mylogin,#myreg').hide();
    $('#userinfo').show().text(loginMail);
    $('#scriptBtn,#comListModelBtn,#monitorBtn,#notifyBtn,#structListModelBtn').show();
    postUserData = {
      loginmail: loginMail
    };
    $.post('/user/getUser', postUserData, function(_data) {
      var regionId;
      if (_data.isRam === 0) {
        regionId = $.cookie('regionId') ? $.cookie('regionId') : 'cn-hangzhou';
        $("input[name=ram-regionCheck][value=" + regionId + "]").iCheck('check');
        $('#ramModal').modal('show');
        $('#loginModal').modal('hide');
      } else {
        $.cookie('isRam', '1');
        location.replace('/new');
      }
    });
  },
  mainLoginsucback: function(i, source) {
    var loginMail, loginokmsg, postUserData;
    loginMail = $.cookie('loginMail');
    $('#usermail').text(loginMail);
    $('#mylogin,#myreg').hide();
    $('#userinfo').show().text(loginMail);
    $('#comListModelBtn,#scriptBtn,#monitorBtn,#notifyBtn,#structListModelBtn').show();
    loginokmsg = $('#login-msg-ok');
    loginokmsg.html('<p style="text-align:center">登录成功</p>');
    if (global.checkTimeout) {
      clearTimeout(global.checkTimeout);
    }
    setTimeout(function() {
      loginokmsg.stop(true, true);
      loginokmsg.fadeOut();
    }, 2000);
    loginokmsg.stop(true, true).fadeIn();
    loginFunc.isAdmin(loginMail);
    if ($.cookie('savetype')) {
      switch ($.cookie('savetype')) {
        case 'achi':
          $('#saveBtn').trigger('click');
          break;
        case 'layer_confirm':
          $('#layer_confirm').trigger('click');
          break;
        case 'ecs_confirm_pay1':
          $('#ecs_confirm_pay1').trigger('click');
          break;
        case 'rds_confirm':
          $('#rds_confirm').trigger('click');
          break;
        default:
          $.removeCookie('savetype');
      }
      $.removeCookie('savetype');
    }
    $('#loginModal').modal('hide');
    postUserData = {
      loginmail: loginMail
    };
    $.post('/user/getUser', postUserData, function(_data) {
      var regionId;
      if (_data.isRam === 0) {
        regionId = $.cookie('regionId') ? $.cookie('regionId') : 'cn-hangzhou';
        $("input[name=ram-regionCheck][value=" + regionId + "]").iCheck('check');
        $('#ramModal').modal('show');
      } else {
        $.cookie('isRam', '1');
      }
    });
    domFunc.initStructListModel();
    domFunc.loginSuccessExec();
  },
  loginModalRegClick: function() {
    $('#label-error').text('');
    $('#loginModal').modal('hide');
    $('#regModal').modal('show');
  },
  isAdmin: function(mail) {
    var postData;
    postData = {
      mail: mail
    };
    tools.post('/adminlist/isadmin', postData, loginFunc.isAdminCallback);
  },
  isAdminCallback: function(_data) {
    if (!((_data === 'err') || (_data === '0'))) {
      $("#saveModelBtn").show();
      $("#saveBtn").hide();
    }
  },
  loginInputKeydown: function(e) {
    if (e.keyCode === 13) {
      $('#btn-login').click();
    }
  },
  regInputKeydown: function(e) {
    if (e.keyCode === 13) {
      $('#btn-reg').click();
    }
  },
  userinfoClick: function() {
    var isnew;
    isnew = loginFunc.isNew();
    if (isnew) {
      loginFunc.loginOutClick();
    } else {
      $('.dropdown').dropdown();
    }
  },
  onLoginRegModalHide: function() {
    $.removeCookie('savetype');
  }
};
