// Generated by CoffeeScript 1.6.3
var AbsJiankong;

AbsJiankong = function(params) {
  var comGroup, textWrapGroup, titleText, _config, _params;
  _params = params || {};
  _config = {
    kind: 'jiankong'
  };
  _params = $.extend({}, _config, _params);
  comGroup = new AbsCom(_params);
  titleText = new kk.Text({
    x: 30,
    y: 86,
    width: 50,
    height: 20,
    align: 'center',
    text: "" + (tools.showOverflowText(comGroup.data.name, 10)),
    fontSize: 12,
    fill: 'black'
  });
  textWrapGroup = new kk.Group;
  textWrapGroup.add(titleText);
  comGroup.add(textWrapGroup);
  comGroup.texts = {
    titleText: titleText
  };
  return comGroup;
};
