// Generated by CoffeeScript 1.7.1
var AbsOss;

AbsOss = function (params) {
    var comGroup, textWrapGroup, titleText, _config, _params;
    _params = params || {};
    _config = {
        kind: 'oss'
    };
    _params = $.extend({}, _config, _params);
    comGroup = new AbsCom(_params);
    titleText = new kk.Text({
        x: 30,
        y: 86,
        width: 50,
        height: 42,
        align: 'center',
        text: "" + (tools.showOverflowText(comGroup.data.name, global.titleLenNormal)),
        fontSize: 12,
        wrap: 'char',
        fontFamily: 'monospace',
        fill: 'black'
    });
    textWrapGroup = new kk.Group;
    textWrapGroup.add(titleText);
    comGroup.add(textWrapGroup);
    comGroup.texts = {
        titleText: titleText
    };
    return comGroup;
};
