// Generated by CoffeeScript 1.7.1
var AbsRds;

AbsRds = function (params) {
    var comGroup, dbTypeText, memoryText, statusSynchroImage, textWrapGroup, titleText, _config, _params;
    _params = params || {};
    _config = {
        kind: 'rds'
    };
    _params = $.extend({}, _config, _params);
    comGroup = new AbsCom(_params);
    titleText = new kk.Text({
        x: 30,
        y: 86,
        width: 50,
        height: 42,
        align: 'center',
        text: "" + (tools.showOverflowText(comGroup.data.name, global.titleLenNormal)),
        fontSize: 12,
        fill: 'black',
        wrap: 'char',
        fontFamily: 'monospace'
    });
    dbTypeText = new kk.Text({
        x: 12,
        y: 43,
        text: 'MySQL',
        fontSize: 12,
        width: 80,
        fill: '#000',
        align: 'center'
    });
    memoryText = new kk.Text({
        x: 11,
        y: 63,
        text: '240M',
        fontSize: 12,
        width: 80,
        fill: '#000',
        align: 'center'
    });
    textWrapGroup = new kk.Group;
    textWrapGroup.add(titleText);
    textWrapGroup.add(dbTypeText);
    textWrapGroup.add(memoryText);
    comGroup.add(textWrapGroup);
    comGroup.texts = {
        titleText: titleText,
        dbTypeText: dbTypeText,
        memoryText: memoryText
    };
    statusSynchroImage = new kk.Image({
        x: 35,
        y: -35,
        image: global.images.statusEdit,
        width: 28,
        height: 35,
        visible: false
    });
    comGroup.images.statusSynchro = statusSynchroImage;
    comGroup.add(statusSynchroImage);
    comGroup.data.dbType = 'mysql';
    comGroup.data.dbVersion = '5.1';
    comGroup.data.memory = 240;
    comGroup.data.storage = 5;
    comGroup.data.buyTime = 1;
    comGroup.data.buyType = 'month';
    comGroup.data.openList.isOpen = false;
    return comGroup;
};
